version: "3"

services:
  postgres:
    container_name: product_inventory_management_system-db
    image: postgis/postgis:15-master
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_inventory_management_system
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    command: [ "postgres", "-c", "wal_level=logical" ]
  pgadmin:
    container_name: product_inventory_management_system-pgadmin
    image: dpage/pgadmin4:6.21
    depends_on:
      - postgres
    ports:
      - "5432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@foo.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - $HOME/docker/volumes/pgadmin2:/var/lib/pgadmin/storage
    restart: unless-stopped